version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: release-guard-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - release_guard_postgres_data:/var/lib/postgresql/data

volumes:
  release_guard_postgres_data:
