spring:
  application:
    name: release-guard

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update

# Jira Properties
jira:
  api-instance-url: <jira_api_instance_url>
  api-email: <jira_api_email>
  api-token: <jira_api_token>

# GitHub Properties
github:
  api-url: <github_api_url>
  api-token: <github_api_token>
